name: Serverless CI/CD  

on:
  push:
    branches: ['main']


jobs:
  deploy:
    runs-on:  ubuntu-latest

    steps:
     - name: Checkout repository
       uses: actions/checkout@v4

     - name: Setup Node.js
       uses: actions/setup-node@v4
       with:
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json
      
     - name: Install dependencies
       run: npm install
       working-directory: backend
    

     - name: Install Serverless Framework
       run: npm install -g serverless

     - name: Deploy to AWS
       run: serverless deploy
       working-directory: backend
       env:
         AWS_ACCESS_KEY_ID: ${{ secrets.ACCESSKEY }}
         AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRETKEY }}
   