service: auth

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-south-1
  timeout: 15
  environment:
    NODE_ENV: production
    SECKEY: 'hwefvhhjw'
    MONGO_URL: 'mongodb+srv://shahansiddique101:Shahan1234@cluster0.uzufb2d.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0'

functions:
  Authhandler:
    handler: handler.main
    events:
      - httpApi:
          path: /{proxy+}
          method: ANY

package:
  individually: true

custom:
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    exclude: ['aws-sdk']
    target: node20
    platform: node  # ✅ this is required for esbuild (do not remove)
